jmshrv/finamp

lib/components/AlbumImage.dart, lib/components/DownloadsErrorScreen/DownloadErrorListTile.dart, lib/components/DownloadsScreen/DownloadedAlbumsList.dart, lib/components/MusicScreen/MusicScreenTabView.dart, lib/components/PlayerScreen/ProgressSlider.dart, lib/components/ServerSelector/ServerSelectorForm.dart, lib/components/ViewSelector/ViewList.dart, lib/main.dart, lib/models/FinampModels.dart, lib/models/FinampModels.g.dart, lib/models/JellyfinModels.dart, lib/models/JellyfinModels.g.dart, lib/screens/SplashScreen.dart, lib/services/AudioServiceHelper.dart, lib/services/DownloadsHelper.dart, lib/services/JellyfinApi.dart, lib/services/JellyfinApiData.dart, lib/services/MusicPlayerBackgroundTask.dart, pubspec.lock, pubspec.yaml
Instead of using SharedPreferences, store users in a Hive box. This is less jank, as we don't have to convert user data to JSON. Hive is faster and easier to use. MusicScreenTabView is a good example of this. With SharedPreferences, we needed to use a really janky method to get the user's view before getting the items.
This Hive setup will also make multiple users/servers easy, which means that #10 can be closed.
=> Store users with Hive instead of shared preferences

lib/screens/MusicScreen.dart
Fixes #98.
Preview: 
https://user-images.githubusercontent.com/46846000/130363954-43f33c46-efb1-4320-9877-0baea1bc0ae2.mp4
=> Display current library name on app bar in music screen

android/app/src/main/res/drawable/launch_background.xml, android/app/src/main/res/values/styles.xml
A couple of tiny fixes:
- splash screen background changed to black
- on my device the navigation bar kept using light theme, fixed by adjusting color in both splash and normal theme
https://user-images.githubusercontent.com/46846000/132073188-e55b2f45-4e86-4bd2-9fa3-1d6208e56252.mp4
https://user-images.githubusercontent.com/46846000/132073202-0c420414-9a45-490d-90e6-7914c73f8060.mp4
=> Android dark theme improvements

lib/components/PlayerScreen/SongName.dart
Another small addition. It might seem a bit pointless because there's album art already (hopefully making clear which album the song belongs to), but I was thinking about adding an `onTap` callback later, showing the album screen when tapped. 
Same could be done with artist name, but I'm not sure how this would work when there are multiple artists, some of whom don't have their entry in Artists tab (Album Artists, according to JF web client).
=> Add album name on player screen

lib/screens/ViewSelector.dart
Fixes #42.
This might cause issues when user has one `music` library and one or more for audiobooks (of type `books` afaik), as the audiobook library wouldn't get selected. I see three solutions:
- Ignore this, as there's no explicit support for audiobooks in Finamp anyway (yet).
- Start with music library only and make user aware of selector in settings (#148). Maybe mention it in a toast?
- Disable selector skip if any library with type `books` exists.
=> Skip music library selection if there's only one available during setup

lib/components/SettingsScreen/LogoutListTile.dart, lib/screens/SettingsScreen.dart
This PR allows user to select libraries after initial setup without wiping app data. No further explanation needed, here's a video anyway:
https://user-images.githubusercontent.com/46846000/142790308-d952537e-05de-4458-889f-237b949c6bdc.mp4
=> Add library selection button in settings

lib/components/LayoutSettingsScreen/ContentGridViewCrossAxisCountListTile.dart, lib/components/LayoutSettingsScreen/ContentViewTypeDropdownListTile.dart, lib/components/MusicScreen/MusicScreenTabView.dart, lib/components/MusicScreen/SortByMenuButton.dart, lib/components/TabsSettingsScreen/HideTabToggle.dart, lib/models/FinampModels.dart, lib/models/JellyfinModels.dart, lib/screens/MusicScreen.dart, pubspec.yaml
Web Client behavior:
Albums - https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/music/musicalbums.js#L243
Songs - https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/music/songs.js#L157
The Web Client does not have sorting for Artists, Playlists or Genres. The current finamp app provides sorting for all categories.
The Web Client also has different sort options for Albums and Songs. The current finamp app has the same sorting options.
If you want, I can make the behavior exactly as the one in the web client. Let me know in the comments and I'll update this PR accordingly.
=> Matched sorting behaviour to the one that is in the jellyfin web client.

lib/components/AlbumScreen/ItemInfo.dart, lib/components/PlayerScreen/SongName.dart
https://user-images.githubusercontent.com/46846000/177649467-d3f34418-1189-4e74-a389-2ec3562d4da8.mp4
Some issues:
- There's no visual indicator that those spots can now be tapped to navigate to artist/album page.
- Janky handling of TextSpans for artists.
- Artist of a song that isn't albumArtist on any album will have empty artist page (last few seconds of video). Web client shows an "appears on" section for such not-album artists, I'm thinking about adding this feature here too:
=> Tap artist or album name to go to its page in library

lib/components/LayoutSettingsScreen/show_cover_as_player_background_selector.dart, lib/components/LayoutSettingsScreen/show_cover_on_player_background_selector.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/screens/layout_settings_screen.dart, lib/screens/player_screen.dart, lib/services/finamp_settings_helper.dart, pubspec.yaml
A bit of eye candy, disabled by default. 2nd row has dark mode, 3rd row has light mode.
Bright cover|Dark cover|Colorful cover
---|---|---
Some issues:
- occasional low contrast, especially with the gray buffer status slider
- enabling this feature isn't saved to disk, tried to follow https://github.com/hivedb/docs/blob/master/custom-objects/generate_adapter.md but got the white screen about broken config
- bottom bar would probably look better transparent, which additionally would fix contrasting with light theme throughout app
=> Add toggleable blurred coverart player background

lib/services/jellyfin_api.dart, lib/services/music_player_background_task.dart, pubspec.yaml
With device_info_plus_platform_interface 2.6.0 (which is a nested dependency of device_info_plus), getting the Android ID is no longer possible. This functionality is now available through the plugin "android_id".
=> Fix retrieval of Android ID

lib/components/AudioServiceSettingsScreen/stop_foreground_selector.dart, lib/screens/audio_service_settings_screen.dart
As this setting is only used for Android, there's no need to display it on other platforms.
=> Only show StopForegroundSelector on Android

lib/components/PlayerScreen/queue_list.dart
Probably some regression happened at some point.
=> Fix missing album images in queue list

lib/services/progress_state_stream.dart
If you pause playback and open player screen or go to album/artist, causing fresh NowPlayingBar to be created, the ProgressState won't emit anything since AudioService.position doesn't emit position unless playback is in progress. This causes the player to have 00:00 position & duration and grayed out slider, and NPB doesn't appear at all (because snapshot.hasData is false).
This PR reuses last known playback position from audioHandler until AudioService emits new position after unpausing, fixing both issues.
=> Use last known playback position for ProgressState while paused

lib/components/MusicScreen/music_screen_tab_view.dart
When using the keyboard's autocomplete/suggestions while searching, a space is usually appended to the search term. Because this could influence the returned search results, it makes sense to trim the search term before sending it to the server.
=> Trim searchTerm before searching

lib/main.dart
Currently, the error app crashes due to `AppLocalization.of(context)` returning `null`.
This is apparently [a bug in Flutter](https://stackoverflow.com/a/72754385/2475176), and worked around by adding another widget wrapping the Scaffold.
=> :bug: Fix crash in ErrorApp

lib/services/music_player_background_task.dart
Almost every other music app allows the previous button to restart the song when the current song plays for at least 5 seconds or so. Wanted to implement that functionality into this app as well. Also allowed the previous button to always restart the current song if its the first song in the queue instead of doing nothing.
First time doing a PR, hope everything looks okay :)
=> Improved skipToPrevious() functionality

lib/components/MusicScreen/music_screen_tab_view.dart
If an artist has multiple albums in one year, albums may not necessarily follow the release order. Sorting by PremiereDate instead fixes that. If no PremiereDate is set on the item, the server will automatically fall back to ProductionYear.
=> Sort artist albums by PremiereDate instead of ProductionYear

lib/components/AlbumScreen/song_list_tile.dart
This simple PR adds the function to add items to a playlist inside of a playlist.
Currently you have to search for the song itself to add it to a playlist.
Now you can add the song to a different playlist directly in the playlist view
=> Add to playlist in playlist

lib/services/music_player_background_task.dart
As outlined in [my recent comment](https://github.com/UnicornsOnLSD/finamp/issues/87#issuecomment-1064319704) in #87, stop events submitted to the server seem to use the playback progress of the following song that's already playing, which causes scrobbling plugins to drop the listen.
Simply using the song's duration for the stop event works around the issue. Unfortunately, this isn't without problems either, since it'll probably submit a complete listen when skipping or changing a track. Due to my limited experience with the app's architecture, I'm not sure how to fix that.
This PR mainly serves as a first attempt, hoping you or others can develop a better solution.
Note that [the other stop event](https://github.com/Maxr1998/finamp/blob/ea1582e28379b8a9661da080f9affa62e35bd229/lib/servic …
=> :bug: Fix playback stop events using an incorrect position

lib/services/music_player_background_task.dart
Still need to test this thoroughly and fix one added TODO before this is ready for a full review. Wanted to get this out early nonetheless.
On to the basic ideas behind this change: currently, the player reports playback stop events **after** the track index changes, with no easy way to know the previous state.
For that, it subscribes to `_player.currentIndexStream`, which simply maps the (distinct) index from `_player.playbackEventStream`. So, my idea was to drop this index stream completely, and instead handle the changes in the `_player.playbackEventStream` manually by comparing the new and previous index. This comes with the advantage that of knowing the complete previous *state* as well in that handler.
I also heavily rewrote `generatePlaybackProgressInfo` and split it into three …
=> Rework player progress reporting

lib/components/AlbumScreen/song_list_tile.dart, lib/components/MusicScreen/album_item.dart, lib/l10n/app_en.arb, lib/services/audio_service_helper.dart, lib/services/music_player_background_task.dart
I've seen that the UI redesign project intends to cover this, but I thought I'd offer this as a quality-of-life backport for the current UI until that gets released.  This partially covers #221, and maybe covers #92 depending on opinion.  Apologies for any style errors (and for the faux pas of swinging in out of the blue with a PR), my Dart is pretty rusty.
This has been tested on iOS Simulator and an iPhone 11 running iOS 16.6.
Open questions and future work:
- There is no i18n for this, I'm monolingual
- The icon is confusing but `Icons` doesn't really offer anything better than `queue_music`
- There are no toolbar items in the album screen for queuing, seemed like too big of a UX question for the scope of this PR
- Shuffle is horribly broken …
=> Add Play Next & Add to Queue for songs and albums.

android/build.gradle, lib/services/chopper_aggregate_logger.dart, lib/services/http_aggregate_logging_interceptor.dart, lib/services/jellyfin_api.dart, pubspec.lock, pubspec.yaml
Currently, the log screen has a lot of short or empty entries from chopper, aggregating the chopper logs per request and response fixes this. However, this requires the latest chopper version (since the required changes were also contributed by myself), and that required a few more updates. Preferably, you'd make those dependency updates yourself and afterward I rebase this PR.
=> :sparkles: Upgrade chopper and aggregate chopper logs to single entry

lib/components/ArtistScreen/artist_play_button.dart, lib/components/ArtistScreen/artist_shuffle_button.dart, lib/components/MusicScreen/music_screen_tab_view.dart, lib/screens/artist_screen.dart
Implements #424 
Adds a button to play all albums of an artist in both offline mode and online mode. Previously, the artist view in offline mode would just show up as a white screen if albums from multiple artists were downloaded. I had to add a bit of code to music_screen_tab_view.dart to make sure only the albums corresponding with the artist show up. Otherwise all downloaded albums in offline mode would show up in each individual artist view.
Also, how do I setup the environment for the redesign branch? I would have written the code in the redesign branch, but I couldn't get that branch to build. I suspect I just set up the environment incorrectly. 
Before:
After:
=> Playing Directly from Artist Page

lib/components/DownloadsScreen/sync_downloaded_playlists.dart, lib/screens/downloads_screen.dart, lib/services/downloads_helper.dart
@jmshrv This adds a new button to sync the current downloads.
Example: 
You download a playlist via finamp.
You add a track to this playlist via jellyfin.
Current situation: you have to delete the playlist and download it again.
With the new button: It checks for not downloaded files and downloads them too.
=> Sync downloads

lib/main.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/services/finamp_user_helper.dart, lib/services/music_player_background_task.dart, lib/services/offline_listen_helper.dart
Useful if you want to manually export them to ListenBrainz or similar later on.
The biggest problem is that the exported file is not easily viewable at the moment. On newer Android versions, you can only view the files when attached to a computer (or with root permissions). On iOS, it's not possible at all.
However, we can probably build some export feature later on.
=> :sparkles: Store listens when offline or if submission failed

lib/components/LayoutSettingsScreen/FastScrollSelector.dart, lib/components/MusicScreen/music_screen_tab_view.dart, lib/l10n/app_en.arb, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/screens/layout_settings_screen.dart, lib/services/finamp_settings_helper.dart, lib/services/jellyfin_api.chopper.dart, pubspec.lock
=> :sparkles: Add toggle to disable fast scroller

lib/color_schemes.g.dart, lib/components/AlbumScreen/song_list_tile.dart, lib/components/MusicScreen/view_list_tile.dart, lib/components/PlayerScreen/progress_slider.dart
Couldn't help myself and made some further refinements, as teased in #561.
- Use original Jellyfin colors in dark theme (for the light theme, they're too light, unfortunately)
- Base secondary color upon desaturated primary color (reduced chroma)
- Add a proper tertiary color based on the purple Jellyfin accent - right now, it doesn't seem to be used anywhere, though
- Make dark theme backgrounds slightly darker
- Use the secondaryContainer color for the drag-to-queue indicator
- Make progress slider inactive color 50% opaque to be less harsh on the eyes
=> :eyes: Further tweak color scheme

ios/Podfile.lock, lib/components/MusicScreen/album_item.dart
Up until now albums and playlists were fetched from the server when adding them to the queue, even if offline mode was active.  
This PR changes the behavior to instead use the downloaded items for these actions instead.
This fix will probably also need to be implemented for the redesign.
=> Fix adding playlists/albums to queue in offline mode

lib/services/jellyfin_api.dart
By default, the DateCreated field is missing from the Jellyfin Items response. This causes the DateCreated field to always be null on BaseItemDtos, so it's not available for sorting when offline.
By adding the field name to the defaultFields, this is resolved. However, all items will have to be resynced before sorting works offline.
I also sorted the fields and changed the field name capitalization to match the Jellyfin API docs. The unchanged fields aren't mentioned there, so I'm not sure they're even necessary.
Fixes #444. Targeting the main branch, but should be trivial to port to the redesign branch.
=> :bug: Fix sort by DateCreated not working when offline

lib/services/music_player_background_task.dart, lib/services/playback_history_service.dart
Tried to improve behavior when playing or skipping past end of queue with loop mode set to one track or none.  The queue now ends up paused at the start of the first track.
=> [Redesign] Improved end of queue behaviour with alternate loop modes

lib/components/PlayerScreen/queue_list.dart
Fades out top of queued tracks list to prevent overlap with text.  Also hides jump to current track button when not scrolled away.
=> [Redesign] Prevent text ovelap in queue

lib/components/MusicScreen/music_screen_tab_view.dart, lib/components/TabsSettingsScreen/hide_tab_toggle.dart, lib/screens/tabs_settings_screen.dart, lib/services/finamp_settings_helper.dart
Hi! First of all, thank you for building this awesome app and making it open source!
This PR contains just a tiny change that makes the drag handle icon visible for the items in the Tabs list.
Since there was no drag handle on the items of the tabs list, I was not aware of the possibility to reorder the tabs, and I wanted to implement it. But taking a look at the code, I saw that the feature was already there. So I just uncommented one line to make the handle visible.
I do not know if that line was left commented out because it caused other issues or for other reasons, but from my (not extended) tests I did not notice any issue.
Hope this can help!
=> Enable drag handle for items in tabs list

lib/models/finamp_models.dart, lib/screens/transcoding_settings_screen.dart, lib/services/downloads_service_backend.dart
Switch AAC transcodes to use .aac container.  It seems to already work fine with jellyfin 10.8, and I think it works with iOS?  And we know that AAC in .m4a actually doesn't seem to work.  It also seems to scrub properly on android, unlike m4a.  Also, now uses correct file extension on local paths.
=> [Redesign] Transcoded downloads tweaks

lib/components/AlbumScreen/download_button.dart, lib/components/AlbumScreen/song_menu.dart, lib/l10n/app_en.arb, lib/models/finamp_models.dart
Used the same masking technique as the song queue to prevent text overlap in song menu.  Slightly re-arranged options.  Increased default menu height when opened - does the existing behavior of starting halfway up make sense on larger phones?  To me it's fairly irritating because it means needing two gestures on both open and close to access the majority of the menu options.
=> [Redesign] Song menu tweaks

lib/components/AlbumScreen/song_menu.dart, lib/components/MusicScreen/music_screen_tab_view.dart, lib/components/PlayerScreen/player_screen_appbar_title.dart, lib/components/PlayerScreen/queue_list_item.dart, lib/models/finamp_models.dart, lib/screens/player_screen.dart, lib/services/downloads_service_backend.dart, lib/services/jellyfin_api_helper.dart
Fixes the .song extension applied to all downloaded original songs, which breaks iOS playback.  Also includes a couple other random tweaks I had in the branch:
- A basic fix to the fast scroller accent issue by just ignoring any items with characters beyond z.
- Queue item padding tweak.
- Apply ''Prioritize cover" player setting to landscape mode as well as portrait.
- Just make airplay button white because it can't change theme when switching songs.
Tell me if you want a cleaner version.
=> [Redesign] Fix non-transcoded downloads + tweaks

lib/components/MusicScreen/music_screen_tab_view.dart
- Use Dart's built-in `compareTo` function to compare the sort order of current vs. selected letter
- This should handle stuff like accented characters for us, in a way that is logical to users
- Simplify logic a bit
- The target offset of the animation doesn't always match up with the final item offset, resulting in a sudden jump/jerk at the end. That seems to be a library bug
I also tried somehow calculating the animation duration based on the distance that needs to be scrolled to reduce lagging, but I couldn't get it to work (only in a few random cases that I couldn't reproduce). The idea was dividing the offset from current position to target position by the viewport height, and then multiplying that by 200ms (or something similar), clamping to a minimum and maximum value.  
My logic …
=> Fix fast scroller tripping over accented characters

lib/components/PlayerScreen/song_name_content.dart, lib/components/QueueRestoreScreen/queue_restore_tile.dart, lib/components/now_playing_bar.dart, lib/screens/blurred_player_screen_background.dart, lib/screens/player_screen.dart, lib/services/music_player_background_task.dart, lib/services/queue_service.dart
Save empty queue as latest when stopping playback, but still prevent empty queues from being archived with timestamps.  This prevents the stopped queue from being automatically reloaded if the app is restarted, and also allows the stopped queue to be immediately restored from the restore queue screen if it was closed accidentally.  Also, disables stop gesture in line with existing setting.
=> [Redesign] Queue restore improvments when stopping playback.

lib/components/now_playing_bar.dart, lib/screens/blurred_player_screen_background.dart, lib/screens/player_screen.dart, lib/services/player_screen_theme_provider.dart
If the app changed theme while in the background, do not animate from the last foreground theme to the current theme when returning to foreground.  Just switch to the latest theme as quickly as possible.
=> [Redesign] Skip theme transition animation if app was in background

lib/services/playback_history_service.dart, lib/services/queue_service.dart
If we swipe to add to the queue after launching the app (when no queue exists), the new audio source will temporarily be added to the `_queueAudioSource`, but since the `_audioHandler` doesn't know this queue yet, `_queueFromConcatenatingAudioSource` will still see an empty queue, and thus ignore the new element. Immediately registering the audio source to the audio handler resolves this issue. Furthermore, since the two elements are only written once, they can be final.
=> Make sure audio handler knows queue from the start

lib/components/AddToPlaylistScreen/add_to_playlist_list.dart, lib/components/AddToPlaylistScreen/new_playlist_dialog.dart, lib/components/AlbumScreen/preset_chip.dart, lib/components/AlbumScreen/song_menu.dart, lib/components/AlbumScreen/speed_menu.dart, lib/components/LanguageSelectionScreen/language_list.dart, lib/components/MusicScreen/alphabet_item_list.dart, lib/components/MusicScreen/music_screen_tab_view.dart, lib/components/PlayerScreen/queue_list.dart, lib/components/ViewSelector/no_music_libraries_message.dart, lib/main.dart, lib/screens/audio_service_settings_screen.dart, lib/screens/customization_settings_screen.dart, lib/screens/interaction_settings_screen.dart, lib/screens/player_screen.dart, lib/screens/queue_restore_screen.dart, lib/screens/settings_screen.dart, lib/screens/tabs_settings_screen.dart, lib/screens/transcoding_settings_screen.dart, lib/screens/view_selector.dart, lib/screens/volume_normalization_settings_screen.dart, lib/services/jellyfin_api_helper.dart
Due to an error when scrolling on desktop, I previously removed the Scrollbar widgets from many lists.  However, it seems that while scrollbars are still shown on desktop, they are not on mobile.  This corrects that and shows scrollbars on mobile while also cleaning up the remaining Scrollbar widgets with no explicit ScrollController.  Also, I noticed some blinking on the lyrics screen slide transition, so I fixed that.
=> [Desktop Beta] Cleanup scrollbars

CONTRIBUTING.md, assets/finamp.desktop.m4
Instead of making packagers ship this themselves, this should be a predefined template in the upstream repo.
=> Add desktop entry m4 template

lib/components/DownloadsScreen/item_file_size.dart, lib/components/MusicScreen/music_screen_tab_view.dart, lib/models/finamp_models.dart, lib/models/jellyfin_models.dart, lib/services/downloads_service.dart, lib/services/downloads_service_backend.dart, lib/services/jellyfin_api_helper.dart
Download orphan tracks which are not contained in any album when downloading library.  Actual functionality not yet tested as I don't have any orphan tracks.
Also forces full metadata refresh during download repair, adds some comments, cleans up unneeded childCount references, fixes showing deleting instead of syncing on subitems on the downloads screen, update playlist image on sync, and properly remove syncFailed state.
=> [Redesign] Download orphan tracks with library

android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Removed while regenerating icons in 37897816ca0484d7c47388275bbdf35b73b6d469.
=> Restore monochrome icon on Android

lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/models/jellyfin_models.dart, lib/screens/blurred_player_screen_background.dart, lib/services/downloads_service_backend.dart
Adds several more types which will be treated like songs by download system, like Movie or Video.  They may or may not download correctly, but hopefully they shouldn't throw errors?
Changed default action when parsing a BaseItemDto of unknown type from throwing an error to creating a collection which will not have any children when syncing.  Hopefully this keeps the download system from ever breaking the UI.
=> [Redesign] Add more BaseItemDtoTypes

lib/components/AlbumScreen/download_dialog.dart, lib/components/AlbumScreen/song_list_tile.dart, lib/components/PlayerScreen/feature_chips.dart, lib/models/finamp_models.dart, lib/models/jellyfin_models.dart, lib/services/downloads_service_backend.dart, lib/services/jellyfin_api_helper.dart, lib/services/metadata_provider.dart
Fixes an issue where a null check error is thrown while syncing older finampCollections that do not have a FinampCollection object attached.  I haven't actually tested it with a legacy item yet.
=> [Redesign] Fix syncing legacy FinampCollections.

assets/com.unicornsonlsd.Finamp.metainfo.xml
Fixes Appstream validation of the metainfo file. This should resolve the flathub build failure.
=> Appstream validation for metainfo.xml

assets/com.unicornsonlsd.finamp.metainfo.xml
Get metainfo summary under 35 characters so we meet the Flathub high quality app data criteria.
=> Get metainfo under 35 chars

lib/components/PlayerScreen/queue_source_helper.dart
Use the correct ID so that queue items removed from a playlist actually stop showing up as in it.
=> [Redesign] Fix queue item playlist removal cache

android/app/src/main/kotlin/com/unicornsonlsd/finamp/MediaItemContentProvider.kt, lib/services/queue_service.dart
Fixes an issue where artwork doesn't display in the media notification or android auto/automotive if the server uses a port number.
The issue was the port number wasn't removed from the URI when passing to the ContentProvider, so it wasn't able to find it.
Additionally, the ContentProvider would encode the URI's authority (breaking the URL) unless we set the encoded authority directly.
=> Fix URI passed to ContentProvider

lib/components/AlbumScreen/download_dialog.dart, lib/l10n/app_en.arb
Fixes *"Download original - x.xx GB null"* transcode option when downloading playlists.
Originally reported by Tarulia in the Finamp Discord.
=> Fix stray "null" in download transcode dialog

lib/services/album_image_provider.dart
Offline images were previously resized with a policy of `exact`, which caused them to be weirdly stretched if they weren't square. Setting the policy to `fit` fixes this issue.
=> Fix aspect ratio of non-square offline images

lib/components/MusicScreen/offline_mode_switch_list_tile.dart
Using a transparent inactive track color ensures it matches the elevated drawer background.
=> Fix offline mode switch theme

lib/services/jellyfin_api.dart, pubspec.lock, pubspec.yaml
It seems like the id in the androidDeviceInfo.id is actually a build ID.  I've switched to an ID provided by the app_set_id plugin, which I believe should be unique.
=> [Redesign] Switch Android client ID source.

lib/screens/music_screen.dart
Allows accessing the sidebar by swiping right when on the leftmost tab of the music screen.
=> [Redesign] Access sidebar via gesture

lib/components/PlayerScreen/player_screen_album_image.dart, lib/components/album_image.dart, lib/screens/player_screen.dart, lib/services/album_image_provider.dart, lib/services/keep_screen_on_helper.dart
Attempts to fix the oversized backdrop shadow seen on the player screen with non-square album covers.  Also allows non-square albums to better expand into padding regions if needed to increase their size without affecting controls layout.  Also, I made the keep_screen_on_helper less chatty while tracks are playing.
=> Fix player album image shadow for non-square covers.

lib/components/LoginScreen/login_authentication_page.dart, lib/components/LoginScreen/login_server_selection_page.dart, lib/components/LoginScreen/login_splash_page.dart, lib/components/LoginScreen/login_user_selection_page.dart, lib/screens/login_screen.dart
Fixes the cramped feeling on the page change by moving the padding to the SingleChildScrollView's.
=> fix: login screens side padding

lib/components/ArtistScreen/artist_screen_content.dart
This ensures albums are correctly ordered by release date, if there are more than one within the same year.
I am not sure if the `ProductionYear` sort is still needed here, but it doesn't hurt, I suppose. If the `PremiereDate` is empty, that would mean it's at least sorted by `ProductionYear` like before.
=> Sort albums by PremiereDate on artist screen

lib/services/offline_listen_helper.dart, lib/services/playback_history_service.dart
The boolean expression we currently use for server stop events already works very well, so the same should be used while offline (in the `onTrackChanged` callback). I also added a logging call to the `OfflineListenLogHelper` for good measure.
=> Use same logic for playback stop events and offline listen log

lib/gen/assets.gen.dart, lib/l10n/app_en.arb, lib/main.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/screens/transcoding_settings_screen.dart, lib/services/queue_service.dart
This should hopefully fix #600, and maybe some other issues too.
Seems to work on Android (14), but it would be good if someone could give this a try on iOS and test with a Vorbis file to make sure this is indeed a fix.  
Either way, it probably doesn't hurt to include this setting, even if it doesn't fix the issue.
=> Select transcoding segment container, default to fmp4

lib/services/downloads_service.dart
Skip adding viewIds to migrated playlists as are shouldn't have them.
=> [Redesign] download Migration Fix

lib/components/ArtistScreen/artist_screen_content.dart
Fixes the minor issue where the artist top songs section would also show songs with "0 plays".
=> Only show artist top songs with at least one play

lib/components/now_playing_bar.dart
This prevents the restoring version of the playing bar from clipping under system UI elements.
=> [Redesign] Add SafeArea to playing bar restore widget

lib/l10n/app_fr.arb
I recently discovered Finamp and was totally amazed by how good the app is.
I wrote this text as I translated to explain the changes I made in the translations. My goal/thought are the following:
- To strike a balance between understanding and accuracy (for example: in France, no one says "URL", we simply say "adresse," even though it might be ambiguous; that's how the "average person" refers to URLs).
- In France, we don't translate much in "computing" terms. While there may be a French way of saying something, my priority is to use the most common term. For example, no one says "file de lecture" (playlist); we just say "playlist." Similarly, in France, people use the English word "weekend" to refer to the last two days of the week when we generally don't work. Another example: I don’t …
=> Native french translation of Finamp

lib/components/AlbumScreen/download_button.dart, lib/components/AlbumScreen/track_list_tile.dart, lib/components/DownloadsScreen/downloaded_items_list.dart, lib/components/InteractionSettingsScreen/keep_screen_on_while_charging_selector.dart, lib/components/MusicScreen/music_screen_tab_view.dart, lib/components/PlayerScreen/queue_source_helper.dart, lib/components/favourite_button.dart, lib/l10n/app_en.arb, lib/main.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/screens/album_settings_screen.dart, lib/screens/audio_service_settings_screen.dart, lib/screens/customization_settings_screen.dart, lib/screens/downloads_settings_screen.dart, lib/screens/interaction_settings_screen.dart, lib/screens/layout_settings_screen.dart, lib/screens/lyrics_settings_screen.dart, lib/screens/music_screen.dart, lib/screens/player_settings_screen.dart, lib/screens/settings_screen.dart, lib/screens/tabs_settings_screen.dart, lib/screens/transcoding_settings_screen.dart, lib/screens/volume_normalization_settings_screen.dart, lib/services/android_auto_helper.dart, lib/services/audio_service_helper.dart, lib/services/finamp_settings_helper.dart, lib/services/music_player_background_task.dart, pubspec.lock
Fyi: Some already existing update functions I used dont update the UI, dont know how to fix that
Also idk why `pubspec.lock` got updated, i guess thats normal?
Please double check the defaults ive put there, I believe they are the real defaults since I copied the settings I had which I didnt change much if at all
=> Added Reset Buttons for every Settings Screen

lib/components/AlbumScreen/album_screen_content.dart, lib/components/ArtistScreen/artist_screen_content.dart, lib/components/LanguageSelectionScreen/language_list.dart, lib/components/MusicScreen/music_screen_drawer.dart, lib/components/PlaybackHistoryScreen/playback_history_list.dart, lib/components/PlayerScreen/queue_list.dart, lib/components/now_playing_bar.dart, lib/components/padded_custom_scrollview.dart, lib/components/themed_bottom_sheet.dart, lib/screens/active_downloads_screen.dart, lib/screens/album_screen.dart, lib/screens/downloads_screen.dart, lib/screens/music_screen.dart
Fixes missing bottom padding to allow scrolling all elements past the bottom system UI when now playing bar is inactive and on all screens using CustomScrollViews.
=> [Redesign] Additional fixes to avoid bottom system UI

lib/components/MusicScreen/music_screen_drawer.dart
The drawer padding needs to be entirely handled by internal safearea due to use of SliverFillRemaining
=> Fix settings drawer padding.

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, lib/components/AlbumScreen/album_screen_content.dart, lib/components/AlbumScreen/download_button.dart, lib/components/AlbumScreen/download_dialog.dart, lib/components/ArtistScreen/artist_screen_content.dart, lib/components/DownloadsScreen/item_file_size.dart, lib/components/print_duration.dart, lib/gen/assets.gen.dart, lib/l10n/app_en.arb, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/models/jellyfin_models.g.dart, lib/screens/downloads_settings_screen.dart, lib/services/downloads_service.dart, lib/services/downloads_service_backend.dart, pubspec.lock, pubspec.yaml
Added warning text to downloads dialog for downloads with more than 150 songs.  Download dialog will be shown if this triggers, even if no download settings are needed.  This necessitates a 1 request delay before the dialog shows, which for me can take quite a while if the artist page is still loading because my server is very slow, but which should hopefully be fairly quick for most people.
Additional fixes:
- Reworded custom download location warning to mention the issue with the "Music" directory.
- Padded minutes to two digits for any time over an hour in queue time remaining display.
- Altered app name of android debug builds to make them less confusing when a release build is installed.
=> [Redesign] Downloads Size Warning + other fixes

lib/components/AddToPlaylistScreen/add_to_playlist_list.dart, lib/components/AddToPlaylistScreen/new_playlist_dialog.dart, lib/components/MusicScreen/album_item.dart, lib/l10n/app_en.arb, lib/l10n/app_pl.arb, lib/models/jellyfin_models.dart, lib/models/jellyfin_models.g.dart, lib/services/downloads_service.dart
Allows albums, artists, and the like to be added to playlists.  Jellyfin responds to this by adding all songs the item contains to the playlist without us needing to manually list them out.  Also, an option has been added allowing the user to select public or private visibility when creating a playlist.
=> [Redesign] Adding Albums to Playlists and Private Playlists

lib/screens/album_screen.dart, lib/screens/artist_screen.dart
Scrolling down on a list in the album, artist or genre screen caused the title bar to clash with the iOS status bar.
Mentioned in https://github.com/jmshrv/finamp/issues/1060.
Added `SafeArea()` around the list bodies, now it looks like this:
=> iOS UI Fixes in Album/Artist/Genre Screen Lists.

lib/components/AlbumScreen/track_list_tile.dart, lib/components/AlbumScreen/track_menu.dart, lib/components/DownloadsScreen/item_file_size.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/services/downloads_service.dart, lib/services/downloads_service_backend.dart
The rename caused the entire library to be re-downloaded when repairing downloads, as Finamp uses the download type for the hash when computing the isarId.
=> Rename DownloadItemType.track back to song

lib/components/MusicScreen/music_screen_tab_view.dart, lib/components/MusicScreen/sort_by_menu_button.dart, lib/models/jellyfin_models.dart
- This time it's proper :) #1070
=> sort by play count

lib/components/QueueRestoreScreen/queue_restore_tile.dart, lib/main.dart, lib/screens/music_screen.dart, lib/services/queue_service.dart
Improves the delay between app startup and queue restore completion by moving the call slightly earlier in the boot sequence and skipping an uneeded wait for the saved queues to be committed to disk.  This allows reasonably sized queues to complete their server queries before the music screen queries start instead of after.
=> [Redesign] Improve Queue Restore Speed

lib/components/AlbumScreen/track_list_tile.dart, lib/components/AlbumScreen/track_menu.dart, lib/components/DownloadsScreen/item_file_size.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/services/downloads_service.dart, lib/services/downloads_service_backend.dart
Haven't yet verified my claim that this doesn't break anything, so draft for now. Should be rebase-merged to keep the history later on.
=> Refactor DownloadStub hash calculation and rename DownloadItemType.song to track

lib/main.dart, lib/models/finamp_models.dart, lib/screens/view_selector.dart, lib/services/downloads_service.dart
Due to the errors with setting the migration flags, some users are coming from existing installs but skipping the downloads migration, resulting in the new internal downloads storage location never being created.  This will recreate it for those cases, fixing the issue where users don't have any available download locations.  I considered running the full migration, but I'm pretty sure that would just break things if done after the new download system has potentially already had other changes committed.
=> [Redesign] Fix missing internal downloads location

CONTRIBUTING.md, android/app/build.gradle
This change makes it possible to set an alternative keystore for debug builds. By default, debug builds use an auto-generated keystore that's managed by the Android Gradle plugin. To use your own keystore, you need to supply its path in the property `debugKeystoreFile` in `key.properties` and also set the `debugKeystorePassword`, `debugKeyAlias` and `debugKeyPassword` properties to their respective values.
Release builds already use a separate configuration.
I usually sign my builds with my own constant keystore, makes it easier to sync it between computers. It also helps when testing the debug build with release data on my devices (commenting out the `applicationIdSuffix`).
Previously, I always had to exclude these local changes from commits.
=> Allow specifying keystore for debug builds

lib/l10n/app_en.arb, lib/screens/lyrics_screen.dart
When the 'Show album before lyrics' setting in the Layout & Theme lyrics view tab is ~~enabled~~ disabled, the album cover is hidden, resulting in a blank space being left behind. Now the lyrics start at the top of the screen. 
Before:
After:
I also removed the album cover when no lyrics are available becuase I think it makes a bit more scenes:
=> Remove blank space when 'show album before lyrics' is disabled

lib/services/jellyfin_api_helper.dart
This bypasses the "allow deletion from Server" setting for Playlists since if those get deleted the files are still there.
Request: https://github.com/jmshrv/finamp/issues/458#issuecomment-2751684686
=> Always allow playlist deletion

android/app/build.gradle, lib/main.dart
When finamp is started as a service, there's no PlatformChannel handler, so the Future<> returned by setEnabledSystemUIMode is never completed.
This could use some more investigation, but making it fire-and-forget seems harmless.  There are samples in flutter that do the same thing.
=> Fix hang on splash screen when resuming app via notification

lib/services/jellyfin_api.dart
Fixes some errors on when running JF master branch
```
2025-04-04 00:00:01.523 +02:00] [DBG] [19] Jellyfin.Api.ModelBinders.CommaDelimitedCollectionModelBinder: Error converting value.
System.FormatException: IndexNumber is not a valid value for ItemFields.
---> System.ArgumentException: Requested value 'IndexNumber' was not found.
at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at …
```
=> Remove useless ItemFields from defaultFields

lib/components/PlayerScreen/player_buttons.dart, lib/components/PlayerScreen/player_screen_album_image.dart, lib/components/PlayerScreen/queue_list.dart, lib/components/audio_fade_progress_visualizer_container.dart, lib/components/now_playing_bar.dart, lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/screens/audio_service_settings_screen.dart, lib/services/finamp_settings_helper.dart, lib/services/finamp_settings_helper.g.dart, lib/services/media_state_stream.dart, lib/services/music_player_background_task.dart, lib/services/queue_service.dart, pubspec.lock, pubspec.yaml
Hello, 
I tried implementing the feature requested in #799. I'm quite new to Flutter and Open Source so if there is anything I should improve just let me know :)
The huge diff in `finamp_models.dart` seems to be an issue with reformatting (?).
All in all this PR adds:
1. Fade-in setting, for fading in audio on resume. Fade-in is disabled by default by using a value of 0.
2. Fade-out setting, for fading out audio on pause. Fade-out is disabled by default by using a value of 0.
I could not figure out why, but on initial playback the fade-in does not seem to work, only on resume and pause.
I did not want to add too many new settings, thus the step size for fade-in and fade-out are hardcoded to 50ms for now.
=> Add audio fade-in and fade-out with corresponding settings

lib/components/AlbumScreen/album_screen_content.dart, lib/components/AlbumScreen/track_menu.dart
>  I just noticed in the code that deleting something from the tracks tab will open the parent album instead of refreshing the tab. I think we might want to change that?
Also it seems like there's an error when deleting a track from the tracks tab. The deletion goes through, but the menu doesn't close and (flawed) navigation doesn't happen.
If you could take a look that would be great! Should be a simple fix :)
\- Chaphasilor
___
I believe this is fixed now. Im not a 100% sure if my logic here is sound though.
=> Wrong Navigation when Deleting

lib/main.dart, lib/services/queue_service.dart
Fixes: #1132
When the app is restarted from the notification to continue playback, `AudioService.onPlay` will be called, and the play state propagates through various async queues.
This change attempts to avoid anything cancelling out that play state.
- `initializePlayer` could do that by playing an empty queue, which immediately stops.
- `_replaceWholeQueue` could do that via its `pause` and `stopPlayback` calls.
I'm worried the potential problems this could cause, but I haven't found anything obviously broken on android yet.
Qs
- is there anything in `stopPlayback` that still needs to be done in `_replaceWholeQueue`?
```
Future<void> stopPlayback() async {
queueServiceLogger.info("Stopping playback");
archiveSavedQueue();
if (_savedQueueState == SavedQueueState.pendingSave) { …
```
=> fix: playback fails to resume from media notification after app is killed (android)

android/app/build.gradle, android/app/src/main/kotlin/com/unicornsonlsd/finamp/MediaItemContentProvider.kt
This can happen when loading especially large files like GIF cover arts. Unfortunately, the crash happens within (very old) framework code, so we have to copy the called function and write our own version that simply catches the exception.
Fixes #1185.
=> Fix crash in MediaItemContentProvider when the pipe breaks

lib/l10n/app_en.arb, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/screens/customization_settings_screen.dart, lib/services/finamp_settings_helper.g.dart, lib/services/music_player_background_task.dart
enabling a shuffle button on the android notification by uncommenting the preexisting code XD, close #291 .
=> added shuffle button to the notification screen

lib/components/AlbumScreen/track_menu.dart, lib/components/PlayerScreen/player_buttons_more.dart, lib/components/PlayerScreen/queue_list.dart, lib/l10n/app_en.arb
This change adds a button in the queue sheet to clear the current queue (and stop playback). Currently, you can do this only by swipe-dismissing the now playing bar, but this only works while not in dual-pane mode (e.g. in landscape mode or on large devices) and isn't as obvious. Another alternative is dismissing the playback notification. The new button should provide a more explicit way to invoke this action.
<details>
<summary>Screenshots</summary>
</details>
Unfortunately, I currently get a flutter error when invoking the button, but only while on debug builds in portrait mode:
<details>
<summary>Error message</summary>
</details>
However, I can reproduce the same issue while being on the queue list and dismissing the playback notification, so it doesn't appear to be caused by my …
=> Allow clearing the queue from within the queue

lib/components/AlbumScreen/album_screen_content_flexible_space_bar.dart, lib/components/AlbumScreen/track_menu.dart, lib/components/ArtistScreen/artist_screen_content_flexible_space_bar.dart, lib/components/album_image.dart
The goal is to be able to tap the small album art image in the FlexibleSpaceBar header to reveal a larger version of the album art that is full-width on a mobile device.
- reuse the same image (ideally cached) rather than pulling over the network again
- incorporate a smooth animation as the image magnifies
- keep the area above and below the enlarged image transparent, to view the AlbumScreen behind
- use a "throw away" gesture to get rid of the album art
- also tapping outside the bounds of the image will dismiss it
- https://github.com/jmshrv/finamp/issues/785
=> Tap to enlarge `AlbumImage` on `AlbumScreen`

lib/main.dart, lib/services/jellyfin_api_helper.dart, lib/setup_logging.dart
Stop riverpod from eating errors inside providers.  Prevent error during AutoOffline.startWatching from the settings provider not being fully initialized.  Properly log errors that occur outside of flutter stack frames.  Always create snackbar for assert failures to reduce the chance that they're missed while debugging.  Throw assert error if jellyfin api calls occur during widget build().
=> [Redesign] Improve error handling

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml, lib/main.dart, lib/services/jellyfin_api_helper.dart, pubspec.lock, pubspec.yaml
This fixes https://github.com/jmshrv/finamp/issues/106
Frustratingly, Dart/Flutter ignores user-installed certificates. Working around this requires rooting your Android device to install certificates as "system" certs, which isn't an option for all people.
This is a known issue with Dart, see
https://github.com/dart-lang/sdk/issues/50435 and
https://github.com/flutter/flutter/issues/56607 for details.
This depends on my fork of
`johnstef99/flutter_user_certificates_android`, which I've sent a PR for here
<https://github.com/johnstef99/flutter_user_certificates_android/pull/2>. If y'all don't like the supply chain implications of that, I'm happy to inline the implementation here instead.
I opted not to make this configurable as I don't see the value. People using finamp are sophisticated …
=> Add support for Android user-installed certificates

CONTRIBUTING.md, flake.nix, lib/components/PlayerScreen/feature_chips.dart, lib/components/VolumeNormalizationSettingsScreen/volume_normalization_mode_selector.dart, lib/l10n/app_en.arb, lib/main.dart, lib/models/finamp_models.dart, lib/models/finamp_models.g.dart, lib/services/current_track_metadata_provider.dart, lib/services/metadata_provider.dart, lib/services/music_player_background_task.dart, lib/services/queue_service.dart
This PR uses album gain separately fetched from jellyfin server via `currentTrackMetadataProvider`.
<details>
<summary>Previous text</summary>
This fixes https://github.com/jmshrv/finamp/issues/1102.. and adds a bunch of new bugs (don't know any but it is inevitable, I know)
I had a bunch of ideas how to fix that, however I found [this issue in jellyfin](https://github.com/jellyfin/jellyfin/issues/14346) (can be linked as upstream to #1102 btw), where [it is told](https://github.com/jellyfin/jellyfin/issues/14346#issuecomment-2988016426) that jellyfin averages track gains to get album gain. Knowing that, my implementation averages known part of album, removing the need to do any network requests or changing jellyfin API.
<sup>(however the latter would be very good but I know dotnet (0 …
=> Use album gain outside of album contexts
