jmshrv/finamp

- lib/components/AlbumImage.dart
- lib/components/AlbumScreen/AlbumScreenContent.dart
- lib/components/AlbumScreen/DownloadButton.dart
- lib/components/AlbumScreen/DownloadedIndicator.dart
- lib/components/PlayerScreen/ProgressSlider.dart
- lib/components/ViewSelector/ViewList.dart
- lib/main.dart
- lib/models/JellyfinModels.dart
- lib/models/JellyfinModels.g.dart
- lib/screens/AlbumScreen.dart
- lib/screens/DownloadsScreen.dart
- lib/screens/PlayerScreen.dart
- lib/services/AudioServiceHelper.dart
- lib/services/DownloadsHelper.dart
- lib/services/DownloadsHelper.g.dart
- lib/services/JellyfinApi.chopper.dart
- lib/services/JellyfinApi.dart
- lib/services/MusicPlayerBackgroundTask.dart
- pubspec.lock
- pubspec.yaml
Instead of making loads of random text files, Hive is now used to handle downloads. This is faster and cuts down the amount of stuff that has to be done asynchronously. It is also more suited for syncing and playlists.
> New download system

- lib/components/PlayerScreen/QueueList.dart
- lib/services/MusicPlayerBackgroundTask.dart
This is a rather trivial fix that closes #74. Let me what you think. :)
Note: I only tested this patch on Android, but I didn't touch any platform-dependent code so iOS *should* work too.
> Add pressable queue items

- lib/components/AlbumScreen/SongListTile.dart
With disc numbers (PR hopefully coming soon) this will fix #80.
"Cry" is the first track on second disc of album shown below.
> Add track numbers on album screen

- lib/components/DownloadsScreen/DownloadsOverview.dart
> Fix download screen general item counter

- lib/components/PlayerScreen/FavoriteButton.dart
- lib/screens/PlayerScreen.dart
Added a favorite button to the player screen to favorite/remove from favorite a song that is playing. I am very much new to Flutter so open to any input on improvements, both in code and layout.
> Add favorite button to player screen mm

- lib/components/NowPlayingBar.dart
- lib/components/PlayerScreen/ProgressSlider.dart
Tiny UX thing. I've also added 2 comments in `PlayerScreen/ProgressSlider.dart` to avoid mistaking one slider for another.
https://user-images.githubusercontent.com/46846000/157125480-3d968625-d7b3-412d-a0a9-6fe4ef0eeed3.mp4
> Add playback progress bar on NowPlayingBar

- lib/screens/album_screen.dart
See jellyfin/jellyfin-web#3481.
> Sort album tracks by (Parent)IndexNumber, then SortName

- lib/components/DownloadsScreen/downloads_overview.dart
> fix download counter color

- lib/components/PlayerScreen/sleep_timer_dialog.dart
- lib/l10n/app_de.arb
- lib/l10n/app_en.arb
This just replaces the doubled headline with minutes instead
> Add minutes description to sleep timer

- lib/components/now_playing_bar.dart
This adds a simple gesture to swipe up to open the player.
> Add Gesture to swipe up to open the player

- lib/components/now_playing_bar.dart
- lib/services/audio_service_helper.dart
This fixes the issues #344 and #252
You can now play songs in playlists with download Errors
> Fix play with download errors

- lib/services/music_player_background_task.dart
By only keeping one queue for the AudioSources, using the built-in move method and generating the UI queue on the fly, issues when moving items in the queue should be a thing of the past.
> Fix queue modification issues

- lib/components/PlayerScreen/queue_list.dart
> Fix wrong image in queue when deleting item

- lib/components/MusicScreen/sort_by_menu_button.dart
- lib/components/MusicScreen/sort_order_button.dart
- lib/main.dart
- lib/models/finamp_models.dart
- lib/models/finamp_models.g.dart
- lib/screens/music_screen.dart
- lib/services/finamp_settings_helper.dart
> :sparkles: Change sort options to apply per tab

- lib/components/MusicScreen/music_screen_tab_view.dart
> :bug: Fix vertical padding in artist/genre lists

- lib/components/PlayerScreen/control_area.dart
- lib/components/PlayerScreen/player_buttons.dart
- lib/components/PlayerScreen/queue_button.dart
- lib/components/PlayerScreen/queue_list.dart
- lib/components/PlayerScreen/song_info.dart
- lib/components/PlayerScreen/song_name_content.dart
- lib/components/finamp_app_bar_button.dart
- lib/screens/player_screen.dart
Some minor QoL improvements. Should probably rebase this to the regular redesign branch, as the changes are not related to the colors...
Also, the way the queue panel is created isn't ideal, it's basically just code repetition. I tried programmatically pressing the queue button instead, but couldn't get it to work. Would love to have some kind of method for that, which we can pass the current context and then open the panel through a simple function call!
> minor player screen changes

- lib/services/downloads_helper.dart
@jmshrv this adds additional logging and changes the count method to fix this issue:
https://github.com/jmshrv/finamp/issues/415
> try to fix the redownload

- android/app/src/main/kotlin/com/example/finamp/MainActivity.kt
- android/app/src/main/kotlin/com/unicornsonlsd/finamp/MainActivity.kt
there was a folder /com/example/finamp/ which did not match up with the namespace in MainActivity.kt
I know I know this is so very minor to make a pull request but you know how the internet people go, they see an issue and then loose sleep over it for the next 25 years
> fix folder structure

- lib/components/DownloadsScreen/download_error_screen_button.dart
- lib/components/DownloadsScreen/download_missing_images_button.dart
- lib/components/DownloadsScreen/sync_downloaded_playlists.dart
- lib/l10n/app_en.arb
- lib/screens/downloads_screen.dart
Provide tooltip for the sync playlists button and generally refactor download screen action buttons.
> Tweak download screen action buttons

- lib/components/LogsScreen/log_tile.dart
Tweak style and other code improvements.
> :eyes: Improve logs interface

- lib/screens/player_screen.dart
- pubspec.lock
- pubspec.yaml
2nd try adding airplay button for ios, on redesign branch
tested ok on ios device
is the button placemement ok? also not sure what to do about the layout warning...
> Airplay button redesign

- lib/components/AlbumScreen/album_screen_content_flexible_space_bar.dart
- lib/components/AlbumScreen/song_menu.dart
- lib/components/ArtistScreen/artist_screen_content_flexible_space_bar.dart
- lib/components/Buttons/cta_large.dart
- lib/components/Buttons/cta_medium.dart
- lib/components/InteractionSettingsScreen/disable_vibration.dart
- lib/components/MusicScreen/alphabet_item_list.dart
- lib/components/PlayerScreen/player_buttons.dart
- lib/components/PlayerScreen/player_buttons_more.dart
- lib/components/PlayerScreen/player_buttons_repeating.dart
- lib/components/PlayerScreen/player_buttons_shuffle.dart
- lib/components/PlayerScreen/queue_list.dart
- lib/components/PlayerScreen/queue_list_item.dart
- lib/components/PlayerScreen/queue_source_helper.dart
- lib/components/favourite_button.dart
- lib/components/global_snackbar.dart
- lib/components/now_playing_bar.dart
- lib/l10n/app_en.arb
- lib/l10n/app_it.arb
- lib/models/finamp_models.dart
- lib/models/finamp_models.g.dart
- lib/screens/interaction_settings_screen.dart
- lib/screens/player_screen.dart
- lib/services/feedback_helper.dart
- lib/services/finamp_settings_helper.dart
- lib/services/vibration_helper.dart
Hello!
This PR addresses issue #657.
As suggested by @Chaphasilor in [this comment](https://github.com/jmshrv/finamp/issues/657#issuecomment-2027025098) (if I understood correctly), I wrapped the vibration setting check in a class.
I will be waiting for feedback. Hope this can help!
> Add toggle to disable vibration #657

- lib/components/AddDownloadLocationScreen/custom_download_location_form.dart
- lib/components/AlbumScreen/album_screen_content.dart
- lib/components/AlbumScreen/download_dialog.dart
- lib/components/AlbumScreen/song_menu.dart
- lib/components/ArtistScreen/artist_screen_content.dart
- lib/components/DownloadLocationSettingsScreen/download_location_list.dart
- lib/components/DownloadLocationSettingsScreen/download_location_list_tile.dart
- lib/l10n/app_en.arb
- lib/main.dart
- lib/models/finamp_models.dart
- lib/models/finamp_models.g.dart
- lib/services/downloads_service_backend.dart
- lib/services/finamp_logs_helper.dart
- lib/services/jellyfin_api_helper.dart
- lib/services/offline_listen_helper.dart
Moved all database files to ApplicationSupport directory on desktop platforms, which is in appdata/roaming on windows.  Added the ability to set a custom download location as the default.
> [Desktop Beta] Improved file Locations

- lib/components/MusicScreen/alphabet_item_list.dart
- lib/components/PlayerScreen/artist_chip.dart
When a song has no artist/album artist, show and 'Unknown Artist' chip instead of just leaving a hole in the layout.
> [Redesign] Show unknown artist on player screen

- lib/screens/blurred_player_screen_background.dart
Fixes blurred background cache not immediately updating image size when screen size changes to to orientation shifts or other reasons.  I thought I tested this as working, but apparently not.
> [Redesign] Fix blurred cover background when switching orientation.

- lib/components/PlayerScreen/queue_list.dart
- lib/l10n/app_en.arb
- lib/models/finamp_models.dart
Show current track position in queue and total queue length.  I'd also like to show the total and/or remaining duration of the queue, but I can't figure out a good place to put this info.
> [Redesign] Show position in queue

- lib/components/AlbumScreen/preset_chip.dart
- lib/components/PlayerScreen/feature_chips.dart
- lib/screens/lyrics_screen.dart
- lib/screens/player_screen.dart
Tweaks to player screen layout code to improve appearance with large windows.  Alters portrait vs landscape mode criteria on desktop and caps maximum control area size.
> [Desktop Beta] More player screen layout tweaks

- lib/l10n/app_en.arb
For now, I only renamed the user-facing strings.
I noticed that some variables and classes use "song" but some use "track" already, is this intentional?  Maybe I will rename the variables and classes as well in the future when I got familiar enough with the language and codebase.
If I missed one of the user-facing strings or accidentally renamed a variable already, please let me know 😊
> Renamed "Song" to "Track" in app_en.arb

- lib/components/AlbumScreen/download_dialog.dart
> [Redesign] Fix transcoding prompt

- .github/workflows/build.yml
- .github/workflows/upload-assets.yml
@Chaphasilor sorry looks like I missed a bit
> Bundle metainfo.xml in linux builds

- assets/com.unicornsonlsd.finamp.metainfo.xml
Needed to fix https://github.com/flathub/com.unicornsonlsd.finamp/pull/2
> Fix release order for appstream validation

- lib/components/MusicScreen/music_screen_tab_view.dart
Fix refresh of music screen on phones by actually calling the refresh function.
> [Redesign] Refresh fix

- lib/l10n/app_en.arb
- lib/models/finamp_models.dart
- lib/models/finamp_models.g.dart
- lib/services/keep_screen_on_helper.dart
This pull request appends to the Keep Screen On functionality by adding an "Always On" option.
> Add Always On option for Keep Screen On functionality

- lib/services/offline_listen_helper.dart
- lib/services/playback_history_service.dart
Probably needs further adjustments to properly fix the offline listen log, but this one should be a good start.
Also fixed some async/await warnings.
> Remove excessive offline log and fix some warnings

- lib/components/LanguageSelectionScreen/language_list.dart
- lib/components/PlaybackHistoryScreen/playback_history_list.dart
- lib/main.dart
- lib/services/locale_helper.dart
Some minor tweaks to date formatting and locale handling. It would be preferable to not squash these, but to do a rebase merge instead.
> Improve locale handling

- lib/components/MusicScreen/music_screen_tab_view.dart
> [Redesign] Fix sort order 'Random' while offline

- README.md
- lib/l10n/app_en.arb
> Minor typo fixes

- lib/components/AlbumScreen/album_screen_content.dart
Fixes: https://github.com/jmshrv/finamp/issues/1079
> fix(album_screen_content): double download button

- lib/components/now_playing_bar.dart
Im starting early because apparently one cant have two forks? Very weird
Added Haptic Feedback when skipping in both directions and closing the playbar
> [Hackathon] Haptic Feedback for the now playing bar

- lib/components/ArtistScreen/artist_screen_content.dart
Just a little fix for the ArtistScreen that I missed in my previous PR.
The ArtistScreen showed the "emptyFilteredListTitle" even if the info was not yet loaded, wich gives a wrong impression.
I added a Loading Progress Indicator that gets shown until the futures completed for the first time.
> Added Loading Indicator to ArtistScreen + Performance Improvements

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/xml/locales_config.xml
This will add a language picker to the info page for the app for Android 13+ devices.
> feat(android): add locale config for Android 13+

- lib/components/ArtistScreen/artist_screen_content.dart
- lib/components/GenreScreen/genre_screen_content.dart
- lib/components/MusicScreen/music_screen_tab_view.dart
Fix for https://github.com/jmshrv/finamp/pull/1232
Sorry for the oversight. 🙃🤦‍♂️
Now it should be working as expected.
Also some spacing fix for the ArtistScreen and some code formatting.
> [Redesign] Fix genrefiltered Playlist List

- flake.lock
- flake.nix
- lib/screens/view_selector.dart
This is just a small fix to load the selected libraries that we persisted before through saving and showing the saved state value. And it adds a nixos flake to make it easier to develop on NixOS
> fix: Small Fix for showing the selected Libraries consistently in settings page

- lib/extensions/string.dart
- lib/hive_registrar.g.dart
- lib/models/jellyfin_models.dart
- lib/models/jellyfin_models.g.dart
- lib/screens/lyrics_screen.dart
- pubspec.lock
Still far from finished, but this branch already contains a good base to work on, as well as some cleanup that I'll probably push to redesign earlier than the rest.
> Support word-by-word synced lyrics

- lib/components/MusicScreen/offline_mode_switch_list_tile.dart
Changes: https://github.com/jmshrv/finamp/pull/1305#issuecomment-3139050144
> Changed Offline Mode Icons

- lib/components/AlbumScreen/album_screen_content.dart
- lib/components/DownloadLocationSettingsScreen/download_location_list.dart
- lib/components/LoginScreen/login_server_selection_page.dart
- lib/components/LogsScreen/logs_view.dart
- lib/components/PlaybackHistoryScreen/playback_history_list.dart
- lib/screens/lyrics_screen.dart
- lib/screens/queue_restore_screen.dart
- lib/screens/view_selector.dart
- lib/services/music_player_background_task.dart
This just adds some ValueKeys, to the ListViews. Maybe this helps with performance. I have checked most of our ListViews and compared them with suggestions for more performance and in the most parts we are already using the best option.
> Add missing ValueKeys to some ListViews
